[theme]
primaryColor = "#000000"  # Black text
backgroundColor = "#ffffff"  # White background
secondaryBackgroundColor = "#f0f0f0"  # Light gray background for containers
textColor = "#000000"  # Black text
font = "sans serif"
